### ISSUE TITLE
Request For Grade

### ISSUE THREAD

**Issue by sarahdesmarais** [sarahdesmarais/animal-rescue-website#1]
@charlie-quinn

I finally finished my Animal Rescue Website for Loyal Rescue. I believe I deserve an A because firstly the website is fully responsive (it looks great on all screen sizes!). I successfully used the Modular/Grid/Type CSS to its full potential and have a functional application form. 

I’ve also added some animation/transitions to my dog images, added proper favicons at different sizes, and also made sure all my images were compressed and smushed (max size of 250kb) - which are things we learnt this semester. 

When designing my website I also tried to make sure it fit the performance budget and passed the accessibility checks. This is still something I struggle with, and am willing to work more on in the future. I know my performance could improve on this website but would need some extra tips on making it better. I was struggling with Markbot for this assignment which I usually rely on for these tips.

I believe overall my website demonstrates excellent understanding of the material we learnt this semester.

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded. A marking rubric has been sent to your college email address.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@sarahdesmarais ⚠️`Reminder: please close this issue since it has been resolved or expired.`
