### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by sarahdesmarais** [sarahdesmarais/animal-rescue-website#2]
@charlie-quinn

https://docs.google.com/spreadsheets/d/1EzeK5KuwYvltd2iPjmg1wdyODpdwaT6UIv8MyUlEjEY/edit?usp=sharing

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`

**Comment by charlie-quinn** [comment]
@sarahdesmarais ⚠️`Reminder: please close this issue since it has been resolved or expired.`
